### ISSUE TITLE
error while running 

### ISSUE THREAD

**Issue by xori22** [YossiSassi/Get-UserSession#1]
Hi Yossi,

while running the script, after entering the requested user name, I get this error:

Where-Object : Cannot bind parameter 'FilterScript'. Cannot convert the "UserName" value of type "System.String" to type "System.Management.Automation.ScriptBlock".
At C:\sassi\Get-UserSession\Get-UserSession.ps1:84 char:32
+     $global:SessionList | where <<<<  UserName -eq $username
    + CategoryInfo          : InvalidArgument: (:) [Where-Object], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.WhereObjectCommand

**Comment by YossiSassi** [comment]
Hi xori22,

Did you perhaps try to query a username with {} ?
In any case- the results are there - just the username value was not
a String, for some weird reason...

Can you please to run the following - from the same shell/console you ran
the script from (AFTER it finished running and gave you the error):
$global:SessionList | where username -eq $username
<where $username is a valid samAccountName in the domain.

Thanks!
Yossi

**Comment by YossiSassi** [comment]
xori22 -
Try something like :
$global:SessionList | where username -eq Administrator

**Comment by xori22** [comment]
No,
I didn't put any {} in the prompt

I ran the query you wrote but get the same error...

**Comment by YossiSassi** [comment]
Hi Xori22,
1. When you type $global:SessionList, after the script finishes, do you see any results? 
2. Pls try running the script again, but without line 21, meaning remove or comment out this line:
# $ErrorActionPreference = "silentlycontinue" 
do you get other errors? 
p.s. you can see all errors in the session by typing $Error at the end of the script run.

**Comment by YossiSassi** [comment]
Hi Xori22,
Finally I was able to re-produce & FIX the issue :) 
**Please try the latest version from this page.** 
Thank you!
